### ISSUE TITLE
I do not create input data for the CNN models.

### ISSUE THREAD

**Issue by Seaxingzhou** [akulikova64/CNN_protein_landscape#1]
@akulikova64 Hi, thanks for your perfect work in  J Biol Phys.
I want to learn and repeat your results, but I can not use your CNN models because of I don't know the input data structure.
Could you please provide a working example of the CNN models? 
Thanks!

**Comment by danny305** [comment]
The input is described in the paper and is further described in the original paper. 
https://pubs.acs.org/doi/abs/10.1021/acssynbio.0c00345

We did not release the data engineering pipeline just the models. 

You can check out pafnucy or libmolgrid for data engineering libraries that you could tweak.

**Comment by dengqf2313** [comment]
@akulikova64  Hi, thanks for your perfect work.
I tried to disassemble your model(neural_network/fully_trained_models/20A ), but I found the model you offered here was different from your paper(Discovery of Novel Gain-of-Function Mutations Guided by Structure-Based Deep Learning). In your paper, the input dimension of first fully  connected layers is 10800, but that in the model you offered is 400.
Could you please provide a new model?
Thanks!

**Comment by akulikova64** [comment]
Hello,
I am forwarding your message to Danny Diaz, who worked with the CNN models in that paper. 
Best,Anastasiya 
    On Sunday, February 19, 2023 at 07:46:13 AM EST, dengqf2313 ***@***.***> wrote:  
 
 


@akulikova64 Hi, thanks for your perfect work.
I tried to disassemble your model(neural_network/fully_trained_models/20A ), but I found the model you offered here was different from your paper(Discovery of Novel Gain-of-Function Mutations Guided by Structure-Based Deep Learning). In your paper, the input dimension of first fully connected layers is 10800, but that in the model you offered is 400.
Could you please provide a new model?
Thanks!
